# Form implementation generated from reading ui file '1login.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from tkinter import messagebox
from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector

# Kết nối MySQL
def connect_db():
    return mysql.connector.connect(
        host='localhost',
        user='root',
        password='',
        database='qlns_bx_bus'
            )


def login():
    etxtuser = etxtuser.get()
    etxtpass = etxtpass.get()
    conn = connect_db()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM login WHERE USER =%s AND PASSWORD=%s", (etxtuser, etxtpass))
    user = cursor.fetchone()
    conn.close()
    if etxtuser:
        messagebox.showinfo("Thông báo", "Đăng nhập thành công!")
        LOGIN.withdraw()
    else:
        messagebox.showerror("Lỗi", "Sai tài khoản hoặc mật khẩu")

class Ui_LOGIN(object):
    def setupUi(self, LOGIN):
        LOGIN.setObjectName("LOGIN")
        LOGIN.resize(502, 381)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LOGIN.sizePolicy().hasHeightForWidth())
        LOGIN.setSizePolicy(sizePolicy)
        LOGIN.setMinimumSize(QtCore.QSize(451, 381))
        LOGIN.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        LOGIN.setStyleSheet("background-color: rgb(255,255,255);\n"
"")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=LOGIN)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 481, 299))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.userlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.userlayout.setContentsMargins(30, 10, 30, 10)
        self.userlayout.setObjectName("userlayout")
        self.label1_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label1_2.setFont(font)
        self.label1_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label1_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label1_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label1_2.setWordWrap(True)
        self.label1_2.setObjectName("label1_2")
        self.userlayout.addWidget(self.label1_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.layoutuser = QtWidgets.QHBoxLayout()
        self.layoutuser.setContentsMargins(12, 10, 12, 10)
        self.layoutuser.setObjectName("layoutuser")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.layoutuser.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.etxtuser = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget_2)
        self.etxtuser.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.etxtuser.setFont(font)
        self.etxtuser.setStyleSheet("font: 10pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.etxtuser.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.etxtuser.setObjectName("etxtuser")
        self.layoutuser.addWidget(self.etxtuser)
        self.userlayout.addLayout(self.layoutuser)
        self.layoutpass = QtWidgets.QHBoxLayout()
        self.layoutpass.setContentsMargins(12, 10, 12, 10)
        self.layoutpass.setSpacing(0)
        self.layoutpass.setObjectName("layoutpass")
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.layoutpass.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.etxtpass = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget_2)
        self.etxtpass.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.etxtpass.setFont(font)
        self.etxtpass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Times New Roman\";")
        self.etxtpass.setObjectName("etxtpass")
        self.layoutpass.addWidget(self.etxtpass, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.userlayout.addLayout(self.layoutpass)
        self.rbtnviewpasss = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        self.rbtnviewpasss.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rbtnviewpasss.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../IMG/viewpass.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rbtnviewpasss.setIcon(icon)
        self.rbtnviewpasss.setIconSize(QtCore.QSize(24, 24))
        self.rbtnviewpasss.setObjectName("rbtnviewpasss")
        self.userlayout.addWidget(self.rbtnviewpasss)
        self.groupbutton = QtWidgets.QHBoxLayout()
        self.groupbutton.setContentsMargins(12, 10, 12, 20)
        self.groupbutton.setObjectName("groupbutton")
        self.btnlogin = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnlogin.sizePolicy().hasHeightForWidth())
        self.btnlogin.setSizePolicy(sizePolicy)
        self.btnlogin.setMaximumSize(QtCore.QSize(100, 30))
        self.btnlogin.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(255, 0, 0);\n"
"font: 81 11pt \"Rockwell Extra Bold\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("IMG/loginus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnlogin.setIcon(icon1)
        self.btnlogin.setObjectName("btnlogin")
        self.groupbutton.addWidget(self.btnlogin)
        self.btnex = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnex.sizePolicy().hasHeightForWidth())
        self.btnex.setSizePolicy(sizePolicy)
        self.btnex.setMaximumSize(QtCore.QSize(100, 30))
        self.btnex.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 0);\n"
"font: 81 11pt \"Rockwell Extra Bold\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("IMG/ex.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnex.setIcon(icon2)
        self.btnex.setObjectName("btnex")
        self.groupbutton.addWidget(self.btnex)
        self.userlayout.addLayout(self.groupbutton)

        self.retranslateUi(LOGIN)
        QtCore.QMetaObject.connectSlotsByName(LOGIN)

    def retranslateUi(self, LOGIN):
        _translate = QtCore.QCoreApplication.translate
        LOGIN.setWindowTitle(_translate("LOGIN", "LOGIN"))
        self.label1_2.setText(_translate("LOGIN", "LOGIN USER"))
        self.label_2.setText(_translate("LOGIN", "USER:"))
        self.etxtuser.setHtml(_translate("LOGIN", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:10pt; font-weight:400; font-style:normal;\" bgcolor=\"#ffffff\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"C:\\BTL Python\\CODE\\IMG\\username.png\" /></p></body></html>"))
        self.label_3.setText(_translate("LOGIN", "PASSWORD:"))
        self.etxtpass.setHtml(_translate("LOGIN", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"C:\\BTL Python\\CODE\\IMG\\password.png\" /></p></body></html>"))
        self.rbtnviewpasss.setText(_translate("LOGIN", "VIEW PASSWORD"))
        self.btnlogin.setText(_translate("LOGIN", "LOGIN"))
        self.btnex.setText(_translate("LOGIN", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LOGIN = QtWidgets.QDialog()
    ui = Ui_LOGIN()
    ui.setupUi(LOGIN)
    LOGIN.show()
    sys.exit(app.exec())
